# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'UIViewController-PopUp-Sample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIViewController-PopUp-Sample
  pod 'VisualEffectView', '~> 1.0.4'
end
